$filePath = "c:\Users\USUARIO\OneDrive\Desktop\Proyectos\Menu Refugios\index.html"
$html = Get-Content -Raw -Path $filePath -Encoding UTF8

$newMain = @"
<main class="max-w-5xl mx-auto px-6 py-12">

        <!-- Categoría: Café -->
        <section id="cafe" class="mb-32">
            <div class="border-y-[8px] border-negro py-6 mb-16 bg-brand-dark text-blanco px-4 transform -rotate-1">
                <h3 class="text-4xl md:text-6xl font-serif font-bold uppercase tracking-title text-center">Café</h3>
            </div>

            <!-- Sub: A base de espresso -->
            <div class="mb-16">
                <h4 class="text-2xl md:text-3xl font-serif font-bold uppercase tracking-title text-brand-dark mb-8 inline-block border-b-[6px] border-brand-light pb-2">
                    A base de espresso
                </h4>
                <ul class="space-y-4 md:space-y-6 text-xs md:text-sm font-bold uppercase tracking-widest">
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Tradicional</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$3.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Café de tostión intensa, con notas a chocolate, extraído bajo método de goteo, que le da suavidad y sabor.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Americano</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$6.500</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Café de origen a base de espresso con acidez cítrica y tostión media. ¡Disfruta de sus tonos achocolatados y final a vino!.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Americano Doble</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$7.500</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Café de origen, a base de doble espresso, con acidez cítrica y tostión media. ¡Disfruta de sus tonos achocolatados y final a vino!.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Espresso</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$6.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Un shot corto de nuestro mejor café.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Doppio</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$7.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Doble shot de espresso para un boost de energía y sabor que te hará conquistar el día.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Café Tonic</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$13.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Fusión refrescante y burbujeante que une la intensidad del espresso doble con la chispa de la tónica</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Cortado</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$6.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">A base de espresso con un toque de leche espumada.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Mocaccino</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$9.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Una combinación de espresso, leche cremada y un toque de chocolate.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Latte <span class="inline-flex ml-2 items-center"><svg class="w-4 h-4 inline-block ml-1 text-brand-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"><path d="M8 3v4M12 3v4M16 3v4M5 9h14v7a4 4 0 0 1-4 4H9a4 4 0 0 1-4-4V9zM19 9h2v3h-2"></path></svg><svg class="w-4 h-4 inline-block ml-1 text-brand-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"><path d="M7 6l1 14h8l1-14M6 6h12M14 6l1-4h-4M9 11l2 6M13 11l-1 6"></path></svg></span></span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$10.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Bebida a base café espresso, hielo y sedosa capa de espuma de leche y vainilla.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Latte Caramelo <span class="inline-flex ml-2 items-center"><svg class="w-4 h-4 inline-block ml-1 text-brand-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"><path d="M8 3v4M12 3v4M16 3v4M5 9h14v7a4 4 0 0 1-4 4H9a4 4 0 0 1-4-4V9zM19 9h2v3h-2"></path></svg><svg class="w-4 h-4 inline-block ml-1 text-brand-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"><path d="M7 6l1 14h8l1-14M6 6h12M14 6l1-4h-4M9 11l2 6M13 11l-1 6"></path></svg></span></span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$13.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Bebida a base café espresso, hielo y sedosa capa de espuma de leche y un toque de caramelo.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Capuccino <span class="inline-flex ml-2 items-center"><svg class="w-4 h-4 inline-block ml-1 text-brand-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"><path d="M8 3v4M12 3v4M16 3v4M5 9h14v7a4 4 0 0 1-4 4H9a4 4 0 0 1-4-4V9zM19 9h2v3h-2"></path></svg><svg class="w-4 h-4 inline-block ml-1 text-brand-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"><path d="M7 6l1 14h8l1-14M6 6h12M14 6l1-4h-4M9 11l2 6M13 11l-1 6"></path></svg></span></span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$9.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Café suave a base de doble espresso, con leche cremada, disfrútalo en su forma original.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Capuccino Vainilla Canela <span class="inline-flex ml-2 items-center"><svg class="w-4 h-4 inline-block ml-1 text-brand-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"><path d="M8 3v4M12 3v4M16 3v4M5 9h14v7a4 4 0 0 1-4 4H9a4 4 0 0 1-4-4V9zM19 9h2v3h-2"></path></svg><svg class="w-4 h-4 inline-block ml-1 text-brand-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"><path d="M7 6l1 14h8l1-14M6 6h12M14 6l1-4h-4M9 11l2 6M13 11l-1 6"></path></svg></span></span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$10.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Café suave a base de doble espresso, con leche cremada, finalizado con esencia de vainilla y canela.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Café Chai</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$12.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Un shot de espresso mezclado con té chai, suavizado con leche cremada. Despierta y reconforta al mismo tiempo.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Café Roncrema <span class="inline-flex ml-2 items-center"><svg class="w-4 h-4 inline-block ml-1 text-brand-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"><path d="M8 3v4M12 3v4M16 3v4M5 9h14v7a4 4 0 0 1-4 4H9a4 4 0 0 1-4-4V9zM19 9h2v3h-2"></path></svg><svg class="w-4 h-4 inline-block ml-1 text-brand-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"><path d="M7 6l1 14h8l1-14M6 6h12M14 6l1-4h-4M9 11l2 6M13 11l-1 6"></path></svg></span></span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$13.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Base de capuccino, con un shot de crema de ron y endulzado con caña.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Granizado de café</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$13.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Refrescante combinación de doble espresso, hielos y un toque de salsa de chocolate.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Afogatto</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$13.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Bola de helado de vainilla, ahogado en un trago de espresso.</p></li>
                </ul>
            </div>

            <!-- Sub: A base de Cold Brew -->
            <div class="mb-16">
                <h4 class="text-2xl md:text-3xl font-serif font-bold uppercase tracking-title text-brand-dark mb-8 inline-block border-b-[6px] border-brand-light pb-2">A base de Cold Brew</h4>
                <ul class="space-y-4 md:space-y-6 text-xs md:text-sm font-bold uppercase tracking-widest">
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Cold Brew</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$11.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Café refrescante, infusionado en frio durante varias horas.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Cold Brew Naranja</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$13.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Café refrescante, infusionado en frio, con un toque cítrico de jugo de naranja.</p></li>
                </ul>
            </div>

            <!-- Sub: Bebidas sin café -->
            <div class="mb-16">
                <h4 class="text-2xl md:text-3xl font-serif font-bold uppercase tracking-title text-brand-dark mb-8 inline-block border-b-[6px] border-brand-light pb-2">Bebidas sin Café</h4>
                <ul class="space-y-4 md:space-y-6 text-xs md:text-sm font-bold uppercase tracking-widest">
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Chocolatada <span class="inline-flex ml-2 items-center"><svg class="w-4 h-4 inline-block ml-1 text-brand-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"><path d="M8 3v4M12 3v4M16 3v4M5 9h14v7a4 4 0 0 1-4 4H9a4 4 0 0 1-4-4V9zM19 9h2v3h-2"></path></svg><svg class="w-4 h-4 inline-block ml-1 text-brand-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"><path d="M7 6l1 14h8l1-14M6 6h12M14 6l1-4h-4M9 11l2 6M13 11l-1 6"></path></svg></span></span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$9.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Cacao orgánico al 70% en leche espumosa.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Chai Latte <span class="inline-flex ml-2 items-center"><svg class="w-4 h-4 inline-block ml-1 text-brand-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"><path d="M8 3v4M12 3v4M16 3v4M5 9h14v7a4 4 0 0 1-4 4H9a4 4 0 0 1-4-4V9zM19 9h2v3h-2"></path></svg><svg class="w-4 h-4 inline-block ml-1 text-brand-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"><path d="M7 6l1 14h8l1-14M6 6h12M14 6l1-4h-4M9 11l2 6M13 11l-1 6"></path></svg></span></span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$12.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">De origen hindú a base de té negro. acompañada de distintas especias y plantas.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Matcha Latte <span class="inline-flex ml-2 items-center"><svg class="w-4 h-4 inline-block ml-1 text-brand-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"><path d="M8 3v4M12 3v4M16 3v4M5 9h14v7a4 4 0 0 1-4 4H9a4 4 0 0 1-4-4V9zM19 9h2v3h-2"></path></svg><svg class="w-4 h-4 inline-block ml-1 text-brand-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"><path d="M7 6l1 14h8l1-14M6 6h12M14 6l1-4h-4M9 11l2 6M13 11l-1 6"></path></svg></span></span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$13.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">De origen asiático con múltiples beneficios, saludable y refrescante. (preparada en bebida de almendras).</p></li>
                </ul>
            </div>
            
            <!-- Sub: Infusiones -->
            <div class="mb-16">
                <h4 class="text-2xl md:text-3xl font-serif font-bold uppercase tracking-title text-brand-dark mb-8 inline-block border-b-[6px] border-brand-light pb-2">Infusiones</h4>
                <div class="flex items-center justify-between mb-6">
                    <p class="text-xs md:text-sm font-bold uppercase tracking-widest text-brand-dark">Bebida natural a base de frutas y plantas aromáticas.</p>
                    <span class="bg-[#f4f3f1] px-2 font-bold text-xs md:text-sm">$5.500</span>
                </div>
                <div class="dotted-line border-brand-dark mb-6 opacity-30"></div>
                <ul class="space-y-4 md:space-y-6 text-xs md:text-sm font-bold uppercase tracking-widest pl-4">
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">- Gripal</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Jengibre, limón y miel ayuda a prevenir los síntomas de la gripa.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">- Anti estrés</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Uva y flores de Bach, ideal para momentos de estrés elevados.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">- Calma</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Piña y naranja. estabiliza el sistema nervioso central y disminuye la ansiedad.</p></li>
                    <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">- Frutal</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Mix de frutas deshidratadas, uchuva, fresa, piña.</p></li>
                </ul>
                <p class="text-[10px] md:text-xs text-brand-dark mt-8 normal-case tracking-normal opacity-80 font-bold leading-relaxed">* Puedes solicitar tus bebidas en bebida de almendras por $4.000</p>
            </div>

            <!-- Sub: Metodos -->
            <div class="mb-16 p-8 border-[6px] border-negro bg-brand-light relative">
                <div class="absolute -top-6 -right-6 bg-blanco border-[4px] border-negro p-3 shadow-[4px_4px_0px_rgba(0,0,0,1)] rotate-3 hidden md:block">
                    <p class="font-bold text-negro uppercase tracking-widest text-xs">Destacado</p>
                </div>
                <h4 class="text-3xl md:text-4xl font-serif font-bold uppercase tracking-title text-negro mb-10 flex items-center gap-4">Métodos</h4>
                <ul class="space-y-6 md:space-y-8 text-xs md:text-sm font-bold uppercase tracking-widest">
                    <li class="flex flex-col md:flex-row justify-between group gap-4 items-start md:items-center">
                        <div class="flex items-center gap-4 z-10 bg-brand-light pr-4">
                            <span class="bg-negro text-blanco p-2 md:p-3 rounded-none flex-shrink-0"><svg class="w-8 h-8 md:w-10 md:h-10 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="miter"><path d="M7 8h10v12H7z M12 2v6 M9 2h6 M6 13h12" /></svg></span>
                            <div class="flex flex-col">
                                <span class="transition-colors group-hover:text-blanco text-sm md:text-base">Prensa Francesa</span>
                                <p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-sm group-hover:text-blanco transition-colors">Perfil más redondo y dulce, con cuerpo denso. Se intensifican los sabores a panela y frutas maduras. *Disponible en 2 o 4 tazas.</p>
                            </div>
                        </div>
                        <div class="hidden md:block dotted-line border-negro opacity-50 flex-grow mx-4"></div>
                        <span class="bg-brand-light pl-0 md:pl-4 z-10 md:text-right w-full md:w-auto text-sm md:text-base font-bold whitespace-nowrap">$ 13.000</span>
                    </li>
                    <li class="flex flex-col md:flex-row justify-between group gap-4 items-start md:items-center">
                        <div class="flex items-center gap-4 z-10 bg-brand-light pr-4">
                            <span class="bg-negro text-blanco p-2 md:p-3 rounded-none flex-shrink-0"><svg class="w-8 h-8 md:w-10 md:h-10 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="miter"><path d="M4 4h16l-8 12L4 4z M9 16v4h6v-4" /></svg></span>
                            <div class="flex flex-col">
                                <span class="transition-colors group-hover:text-blanco text-sm md:text-base">V60</span>
                                <p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-sm group-hover:text-blanco transition-colors">Extracción limpia y brillante que resalta notas florales y cítricas. Ideal para percibir su acidez viva. *Disponible en 2 tazas.</p>
                            </div>
                        </div>
                        <div class="hidden md:block dotted-line border-negro opacity-50 flex-grow mx-4"></div>
                        <span class="bg-brand-light pl-0 md:pl-4 z-10 md:text-right w-full md:w-auto text-sm md:text-base font-bold whitespace-nowrap">$ 16.000</span>
                    </li>
                </ul>
            </div>

            <!-- Sub: Otras Bebidas & Cervezas -->
            <div class="grid md:grid-cols-2 gap-12 mt-16">
                <div>
                    <h4 class="text-2xl font-serif font-bold uppercase tracking-title text-brand-dark mb-8 border-b-[6px] border-brand-light pb-2">Otras Bebidas</h4>
                    <ul class="space-y-4 text-xs md:text-sm font-bold uppercase tracking-widest">
                        <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Té Hatsú</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$7.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Amarillo: Carambolo/loto. Blanco: Té blanco/mangostino. Negro: Té negro/limón. Morado: Té blanco/cerezo.</p></li>
                        <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Sodas</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$13.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Refrescante y con sabores de frutas naturales. Frutos rojos (Mora y Uva) • Frutos amarillos (Naranja y maracuyá).</p></li>
                        <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Soda Michelada</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$6.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Bebida gasificada, hielos y limón. Escarchado con sal.</p></li>
                        <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Soda Hatsú</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$6.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Limón y hierbabuena • Sandía y albahaca • Uva Blanca y romero • Frambuesa y rosas.</p></li>
                    </ul>
                </div>
                <div>
                    <h4 class="text-2xl font-serif font-bold uppercase tracking-title text-brand-dark mb-8 border-b-[6px] border-brand-light pb-2">Cervezas Artesanales</h4>
                    <ul class="space-y-4 text-xs md:text-sm font-bold uppercase tracking-widest mb-4">
                        <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Tres Cordilleras</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$12.000</span></div></li>
                        <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Roja Comarca</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$15.000</span></div></li>
                        <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Negra Mordor</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$15.000</span></div></li>
                    </ul>
                    <p class="text-[10px] md:text-xs text-brand-dark normal-case tracking-normal opacity-80 font-normal leading-relaxed">* Espumosa bebida de origen. ¡Disfruta de sus diferentes presentaciones y tonalidades!</p>
                </div>
            </div>
        </section>

        <!-- Categoría: Repostería -->
        <section id="reposteria" class="mb-32">
            <div class="border-y-[8px] border-negro py-6 mb-16 bg-brand-light text-negro px-4 transform rotate-1">
                <h3 class="text-4xl md:text-6xl font-serif font-bold uppercase tracking-title text-center">Repostería</h3>
            </div>

            <div class="grid md:grid-cols-2 gap-16">
                <!-- Sub: Panes -->
                <div>
                    <h4 class="text-2xl md:text-3xl font-serif font-bold uppercase tracking-title text-brand-dark mb-8 border-b-[6px] border-brand-dark pb-2 inline-block">Panes & Salados</h4>
                    <ul class="space-y-4 md:space-y-6 text-xs md:text-sm font-bold uppercase tracking-widest">
                        <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Palito De Queso</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$9.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Elaborado a partir de mantequilla 100% natural, relleno de queso campesino y finalizado con parmesano.</p></li>
                        <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Croissants</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$10.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Tres quesos | Espinaca y queso | Almendras | Pistacho | Cheesecake</p></li>
                        <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Rollo De Canela</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$9.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Hecho con mantequilla natural, crema de canela y frosting de nuez del nogal.</p></li>
                        <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Empanadas Argentinas</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$9.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Fugazzeta | Capresse | Espinaca y queso</p></li>
                    </ul>
                </div>

                <!-- Sub: Tortas y postres -->
                <div>
                    <h4 class="text-2xl md:text-3xl font-serif font-bold uppercase tracking-title text-brand-dark mb-8 border-b-[6px] border-brand-dark pb-2 inline-block">Tortas y Postres</h4>
                    <ul class="space-y-4 md:space-y-6 text-xs md:text-sm font-bold uppercase tracking-widest">
                        <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Torta De Zanahoria</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$13.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Bizcocho de zanahoria, relleno con crema de maní, cubierto con Maní molido.</p></li>
                        <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Torta De Limón y Amapola</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$13.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Bizcocho de limón y semillas de amapola, relleno de crema alimonada de almendras, cubierto con crema de coco.</p></li>
                        <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Muffin de guayaba y queso</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$9.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Elaborado con masa de queso y centro de guayaba, Lo mejor de lo dulce y lo salado.</p></li>
                        <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Galletas</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$9.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Avena | Macadamia | Chocolate | Doble Chocolate | Red Velvet | Pistacho</p></li>
                        <li class="group"><div class="flex items-baseline justify-between"><span class="bg-[#f4f3f1] pr-4 z-10 transition-colors group-hover:text-brand-dark flex items-center">Alfajor</span><div class="dotted-line group-hover:border-negro transition-colors"></div><span class="bg-[#f4f3f1] pl-4 z-10 opacity-90">$3.000</span></div><p class="text-[10px] md:text-xs text-brand-dark mt-1 normal-case tracking-normal opacity-80 font-normal leading-relaxed max-w-xl">Deliciosas galletas rellenas de arequipe.</p></li>
                    </ul>
                </div>
            </div>
        </section>

        <!-- Sección Falsa de Libros -->
        <section id="libros" class="mb-32">
            <div class="border-y-[8px] border-negro py-6 mb-16 bg-brand-dark text-blanco px-4 transform -rotate-1">
                <h3 class="text-4xl md:text-6xl font-serif font-bold uppercase tracking-title text-center">Libros</h3>
            </div>
            <div class="text-center bg-brand-light border-[6px] border-negro p-12">
                <p class="text-xl md:text-2xl font-serif font-bold uppercase tracking-title text-negro">Selección disponible en tienda</p>
                <p class="text-xs md:text-sm font-bold uppercase tracking-widest text-brand-dark mt-4">Nuestros libros rotan cada semana. Visítanos para descubrir nuestras recomendaciones.</p>
            </div>
        </section>

    </main>
"@

$html = $html -replace '(?s)<main class="max-w-5xl mx-auto px-6 py-12">.*?</main>', $newMain

Set-Content -Path $filePath -Value $html -Encoding UTF8
Write-Output "Update applied via PowerShell."
